name: SPlots
main: eu.starify.plots.SPlots
author: AspDev, Rigolleto
version: 1.2.0
api-version: 1.18
website:
description: This plugin allows players to create plots on survival world
depend:
  - Vault
  - WorldBorderAPI
softdepend:
  - Essentials

commands:
  dzialka:
    aliases: [plot,dzialki,d]
    description: Plots command
  challenge:
    aliases: [wyzwania,challenges]
    description: Challenges command
  ranking:
    description: Plots ranking command

permissions:
  ownplots.bypass:
    children:
      - splots.bypass
    description: With this permission you can build on other plots
    default: op
  ownplots.admin:
    children:
      - splots.admin
    description: Permission for admins
    default: op
  ownplots.fly.bypass:
    children:
      - splots.fly.bypass
    description: Bypass fly limit
    default: op